version: "3"

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
    volumes:
      - ./data/:var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d:ro
    deploy:
      placement:
        constraints:
          - node.role==manager
        max_replicas_per_node: 1

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    networks:
      - backend

    secrets:
      - db_password

networks:
  backend:

secrets:
  db_password:
    file: ./db/password.txt

volumes:
  db_data:
