import Head from "next/head";
import Link from "next/link";

export default function Home() {
  console.log("처음 페이지");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Link href="/login">로그인</Link>
    </>
  );
}
